/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["get_health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a document and start its import job */
        post: operations["upload_document_api_documents_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List documents */
        get: operations["list_documents_api_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a document and its import status */
        get: operations["get_document_api_documents__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}/reimport": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reimport a failed document */
        post: operations["reimport_document_api_documents__id__reimport_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a document's chunks */
        get: operations["list_document_chunks_api_documents__id__chunks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a chat session */
        post: operations["create_session_api_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List messages for a session */
        get: operations["list_session_messages_api_sessions__id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stream a RAG answer using Server-Sent Events */
        post: operations["stream_chat_api_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tools/material-checklist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate a material checklist */
        post: operations["material_checklist_api_tools_material_checklist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluations/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List evaluation cases */
        get: operations["list_evaluation_cases_api_evaluations_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluations/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List evaluation runs */
        get: operations["list_evaluation_runs_api_evaluations_runs_get"];
        put?: never;
        /** Create an evaluation run */
        post: operations["create_evaluation_run_api_evaluations_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluations/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an evaluation run */
        get: operations["get_evaluation_run_api_evaluations_runs__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/missing-knowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List missing-knowledge topics */
        get: operations["list_missing_knowledge_api_missing_knowledge_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/missing-knowledge/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a missing-knowledge topic */
        patch: operations["update_missing_knowledge_api_missing_knowledge__id__patch"];
        trace?: never;
    };
    "/api/retrieval-experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List retrieval experiments */
        get: operations["list_experiments_api_retrieval_experiments_get"];
        put?: never;
        /** Create a retrieval experiment */
        post: operations["create_experiment_api_retrieval_experiments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retrieval-experiments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a retrieval experiment */
        get: operations["get_experiment_api_retrieval_experiments__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnswerStyle
         * @enum {string}
         */
        AnswerStyle: "plain" | "legal";
        /** ApiResponse[DocumentItem] */
        ApiResponse_DocumentItem_: {
            /** Code */
            code: number;
            /** Message */
            message: string;
            data: components["schemas"]["DocumentItem"] | null;
        };
        /** ApiResponse[DocumentReimportAccepted] */
        ApiResponse_DocumentReimportAccepted_: {
            /** Code */
            code: number;
            /** Message */
            message: string;
            data: components["schemas"]["DocumentReimportAccepted"] | null;
        };
        /** ApiResponse[DocumentUploadAccepted] */
        ApiResponse_DocumentUploadAccepted_: {
            /** Code */
            code: number;
            /** Message */
            message: string;
            data: components["schemas"]["DocumentUploadAccepted"] | null;
        };
        /** ApiResponse[EvaluationRunDetail] */
        ApiResponse_EvaluationRunDetail_: {
            /** Code */
            code: number;
            /** Message */
            message: string;
            data: components["schemas"]["EvaluationRunDetail"] | null;
        };
        /** ApiResponse[EvaluationRunJob] */
        ApiResponse_EvaluationRunJob_: {
            /** Code */
            code: number;
            /** Message */
            message: string;
            data: components["schemas"]["EvaluationRunJob"] | null;
        };
        /** ApiResponse[ExperimentDetail] */
        ApiResponse_ExperimentDetail_: {
            /** Code */
            code: number;
            /** Message */
            message: string;
            data: components["schemas"]["ExperimentDetail"] | null;
        };
        /** ApiResponse[ExperimentJob] */
        ApiResponse_ExperimentJob_: {
            /** Code */
            code: number;
            /** Message */
            message: string;
            data: components["schemas"]["ExperimentJob"] | null;
        };
        /** ApiResponse[HealthData] */
        ApiResponse_HealthData_: {
            /** Code */
            code: number;
            /** Message */
            message: string;
            data: components["schemas"]["HealthData"] | null;
        };
        /** ApiResponse[MissingKnowledgeItem] */
        ApiResponse_MissingKnowledgeItem_: {
            /** Code */
            code: number;
            /** Message */
            message: string;
            data: components["schemas"]["MissingKnowledgeItem"] | null;
        };
        /** ApiResponse[NoneType] */
        ApiResponse_NoneType_: {
            /** Code */
            code: number;
            /** Message */
            message: string;
            /** Data */
            data: null;
        };
        /** ApiResponse[PageResult[ChunkItem]] */
        ApiResponse_PageResult_ChunkItem__: {
            /** Code */
            code: number;
            /** Message */
            message: string;
            data: components["schemas"]["PageResult_ChunkItem_"] | null;
        };
        /** ApiResponse[PageResult[DocumentItem]] */
        ApiResponse_PageResult_DocumentItem__: {
            /** Code */
            code: number;
            /** Message */
            message: string;
            data: components["schemas"]["PageResult_DocumentItem_"] | null;
        };
        /** ApiResponse[PageResult[EvaluationCase]] */
        ApiResponse_PageResult_EvaluationCase__: {
            /** Code */
            code: number;
            /** Message */
            message: string;
            data: components["schemas"]["PageResult_EvaluationCase_"] | null;
        };
        /** ApiResponse[PageResult[EvaluationRunSummary]] */
        ApiResponse_PageResult_EvaluationRunSummary__: {
            /** Code */
            code: number;
            /** Message */
            message: string;
            data: components["schemas"]["PageResult_EvaluationRunSummary_"] | null;
        };
        /** ApiResponse[PageResult[ExperimentSummary]] */
        ApiResponse_PageResult_ExperimentSummary__: {
            /** Code */
            code: number;
            /** Message */
            message: string;
            data: components["schemas"]["PageResult_ExperimentSummary_"] | null;
        };
        /** ApiResponse[PageResult[MissingKnowledgeItem]] */
        ApiResponse_PageResult_MissingKnowledgeItem__: {
            /** Code */
            code: number;
            /** Message */
            message: string;
            data: components["schemas"]["PageResult_MissingKnowledgeItem_"] | null;
        };
        /** ApiResponse[SessionItem] */
        ApiResponse_SessionItem_: {
            /** Code */
            code: number;
            /** Message */
            message: string;
            data: components["schemas"]["SessionItem"] | null;
        };
        /** ApiResponse[ToolExecutionItem] */
        ApiResponse_ToolExecutionItem_: {
            /** Code */
            code: number;
            /** Message */
            message: string;
            data: components["schemas"]["ToolExecutionItem"] | null;
        };
        /** ApiResponse[list[MessageItem]] */
        ApiResponse_list_MessageItem__: {
            /** Code */
            code: number;
            /** Message */
            message: string;
            /** Data */
            data: components["schemas"]["MessageItem"][] | null;
        };
        /** Body_upload_document_api_documents_upload_post */
        Body_upload_document_api_documents_upload_post: {
            /**
             * File
             * @description PDF, DOC, DOCX or TXT document
             */
            file: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Question */
            question: string;
            answer_style: components["schemas"]["AnswerStyle"];
        };
        /** ChunkItem */
        ChunkItem: {
            /** Id */
            id: number;
            /** Document Id */
            document_id: number;
            /** Chunk No */
            chunk_no: number;
            /** Content */
            content: string;
            /** Vector Key */
            vector_key: string;
        };
        /** CitationItem */
        CitationItem: {
            /** Chunk Id */
            chunk_id: number;
            /** Document Id */
            document_id: number;
            /** File Name */
            file_name: string;
            /** Chunk No */
            chunk_no: number;
            /** Content */
            content: string;
            /** Score */
            score: number;
            /** Retrieval Score */
            retrieval_score: number;
            /** Rerank Score */
            rerank_score: number | null;
            /** Rank No */
            rank_no: number;
        };
        /** CreateSessionRequest */
        CreateSessionRequest: {
            /** Title */
            title?: string | null;
        };
        /** DocumentItem */
        DocumentItem: {
            /** Id */
            id: number;
            /** File Name */
            file_name: string;
            file_type: components["schemas"]["FileType"];
            status: components["schemas"]["DocumentStatus"];
            /** Chunk Count */
            chunk_count: number;
            /** Error Message */
            error_message: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** DocumentReimportAccepted */
        DocumentReimportAccepted: {
            /** Document Id */
            document_id: number;
            status: components["schemas"]["DocumentStatus"];
        };
        /**
         * DocumentStatus
         * @enum {string}
         */
        DocumentStatus: "PROCESSING" | "SUCCESS" | "FAILED";
        /** DocumentUploadAccepted */
        DocumentUploadAccepted: {
            /** Document Id */
            document_id: number;
            /** File Name */
            file_name: string;
            status: components["schemas"]["DocumentStatus"];
        };
        /** EmbeddingSignature */
        EmbeddingSignature: {
            /**
             * Embedding Provider
             * @enum {string}
             */
            embedding_provider: "local" | "api";
            /** Embedding Model */
            embedding_model: string;
            /** Embedding Dimension */
            embedding_dimension: number;
            /** Normalize Embeddings */
            normalize_embeddings: boolean;
        };
        /** EvaluationCase */
        EvaluationCase: {
            /** Id */
            id: number;
            /** Topic */
            topic: string;
            expected_type: components["schemas"]["EvaluationExpectedType"];
            /** Turns */
            turns: string[];
            /** Expected Points */
            expected_points: string[];
            /** Expected Sources */
            expected_sources: components["schemas"]["ExpectedSource"][];
            /** Should Show Compliance */
            should_show_compliance: boolean;
        };
        /**
         * EvaluationExpectedType
         * @enum {string}
         */
        EvaluationExpectedType: "ANSWER" | "REJECT";
        /** EvaluationMetrics */
        EvaluationMetrics: {
            /** Accuracy */
            accuracy: number | null;
            /** Reject Rate */
            reject_rate: number | null;
            /** Citation Hit Rate */
            citation_hit_rate: number | null;
            /** Multi Turn Pass Rate */
            multi_turn_pass_rate: number | null;
            /** Compliance Hit Rate */
            compliance_hit_rate: number | null;
        };
        /** EvaluationResultItem */
        EvaluationResultItem: {
            /** Case Id */
            case_id: number;
            /**
             * Status
             * @enum {string}
             */
            status: "COMPLETED" | "FAILED";
            /** Answer */
            answer: string | null;
            /** Refused */
            refused: boolean | null;
            /** Correct */
            correct: boolean | null;
            /** Source Hit */
            source_hit: boolean | null;
            /** Multi Turn Correct */
            multi_turn_correct: boolean | null;
            /** Compliance Hit */
            compliance_hit: boolean | null;
            /** Citations */
            citations: components["schemas"]["CitationItem"][];
            /** Latency Ms */
            latency_ms: number | null;
            /** Error Message */
            error_message: string | null;
        };
        /** EvaluationRunConfig */
        EvaluationRunConfig: {
            answer_style: components["schemas"]["AnswerStyle"];
            /** Llm Model */
            llm_model: string;
            /** Evaluator Model */
            evaluator_model: string;
            /** Evaluator Prompt Version */
            evaluator_prompt_version: string;
            /**
             * Embedding Provider
             * @enum {string}
             */
            embedding_provider: "local" | "api";
            /** Embedding Model */
            embedding_model: string;
            /** Embedding Normalize */
            embedding_normalize: boolean;
            /** Prompt Version */
            prompt_version: string;
            /** Chunk Size */
            chunk_size: number;
            /** Chunk Overlap */
            chunk_overlap: number;
            /** Top K */
            top_k: number;
            /** Rerank Enabled */
            rerank_enabled: boolean;
            /** Score Threshold */
            score_threshold: number;
        };
        /** EvaluationRunCreate */
        EvaluationRunCreate: {
            /** Name */
            name: string;
            /** Case Ids */
            case_ids?: number[] | null;
            answer_style: components["schemas"]["AnswerStyle"];
        };
        /** EvaluationRunDetail */
        EvaluationRunDetail: {
            status: components["schemas"]["JobStatus"];
            /** Progress Current */
            progress_current: number;
            /** Progress Total */
            progress_total: number;
            /** Error Message */
            error_message: string | null;
            /** Id */
            id: number;
            /** Name */
            name: string;
            config: components["schemas"]["EvaluationRunConfig"];
            metrics: components["schemas"]["EvaluationMetrics"] | null;
            /** Results */
            results: components["schemas"]["EvaluationResultItem"][];
        };
        /** EvaluationRunJob */
        EvaluationRunJob: {
            status: components["schemas"]["JobStatus"];
            /** Progress Current */
            progress_current: number;
            /** Progress Total */
            progress_total: number;
            /** Error Message */
            error_message: string | null;
            /** Run Id */
            run_id: number;
        };
        /** EvaluationRunSummary */
        EvaluationRunSummary: {
            status: components["schemas"]["JobStatus"];
            /** Progress Current */
            progress_current: number;
            /** Progress Total */
            progress_total: number;
            /** Error Message */
            error_message: string | null;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** ExpectedSource */
        ExpectedSource: {
            /** File Name */
            file_name: string;
            /** Chunk No */
            chunk_no: number | null;
        };
        /** ExperimentCaseResult */
        ExperimentCaseResult: {
            /** Config Index */
            config_index: number;
            /** Case Id */
            case_id: number;
            /**
             * Status
             * @enum {string}
             */
            status: "COMPLETED" | "FAILED";
            /** Retrieved Sources */
            retrieved_sources: components["schemas"]["CitationItem"][];
            /** Source Hit */
            source_hit: boolean | null;
            /** Correct */
            correct: boolean | null;
            /** Refused */
            refused: boolean | null;
            /** Retrieval Ms */
            retrieval_ms: number | null;
            /** Error Message */
            error_message: string | null;
        };
        /** ExperimentConfig */
        ExperimentConfig: {
            /** Chunk Size */
            chunk_size: number;
            /** Chunk Overlap */
            chunk_overlap: number;
            /** Top K */
            top_k: number;
            /** Rerank Enabled */
            rerank_enabled: boolean;
            /** Rerank Top N */
            rerank_top_n: number;
            /** Score Threshold */
            score_threshold: number;
        };
        /** ExperimentConfigResult */
        ExperimentConfigResult: {
            /** Config Index */
            config_index: number;
            config: components["schemas"]["ExperimentConfig"];
            /** Accuracy */
            accuracy: number | null;
            /** Reject Rate */
            reject_rate: number | null;
            /** Citation Hit Rate */
            citation_hit_rate: number | null;
            /** Avg Retrieval Ms */
            avg_retrieval_ms: number | null;
        };
        /** ExperimentCreate */
        ExperimentCreate: {
            /** Name */
            name: string;
            /** Case Ids */
            case_ids?: number[] | null;
            answer_style: components["schemas"]["AnswerStyle"];
            /** Configs */
            configs: components["schemas"]["ExperimentConfig"][];
        };
        /** ExperimentDetail */
        ExperimentDetail: {
            status: components["schemas"]["JobStatus"];
            /** Progress Current */
            progress_current: number;
            /** Progress Total */
            progress_total: number;
            /** Error Message */
            error_message: string | null;
            /** Id */
            id: number;
            /** Name */
            name: string;
            embedding_signature: components["schemas"]["EmbeddingSignature"];
            /** Best Config Index */
            best_config_index: number | null;
            /** Config Results */
            config_results: components["schemas"]["ExperimentConfigResult"][];
            /** Results */
            results: components["schemas"]["ExperimentCaseResult"][];
        };
        /** ExperimentJob */
        ExperimentJob: {
            status: components["schemas"]["JobStatus"];
            /** Progress Current */
            progress_current: number;
            /** Progress Total */
            progress_total: number;
            /** Error Message */
            error_message: string | null;
            /** Experiment Id */
            experiment_id: number;
        };
        /** ExperimentSummary */
        ExperimentSummary: {
            status: components["schemas"]["JobStatus"];
            /** Progress Current */
            progress_current: number;
            /** Progress Total */
            progress_total: number;
            /** Error Message */
            error_message: string | null;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /**
         * FileType
         * @enum {string}
         */
        FileType: "pdf" | "doc" | "docx" | "txt";
        /** HealthData */
        HealthData: {
            /** Service */
            service: string;
            /** Database */
            database: string;
            /** Vector Store */
            vector_store: string;
            /** Doc Converter */
            doc_converter: string;
            /** Llm Configured */
            llm_configured: boolean;
            /** Embedding Provider */
            embedding_provider: string;
            /** Embedding Model */
            embedding_model: string;
            /** Embedding Ready */
            embedding_ready: boolean;
            /** Embedding Index Compatible */
            embedding_index_compatible: boolean;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "PENDING" | "RUNNING" | "COMPLETED" | "FAILED";
        /** MaterialChecklistInput */
        MaterialChecklistInput: {
            /** Dispute Type */
            dispute_type: string;
            /** Description */
            description: string;
        };
        /** MaterialChecklistOutput */
        MaterialChecklistOutput: {
            /** Materials */
            materials: string[];
            /** Note */
            note: string;
        };
        /** MessageItem */
        MessageItem: {
            /** Id */
            id: number;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
            /** Rewritten Question */
            rewritten_question: string | null;
            answer_style: components["schemas"]["AnswerStyle"] | null;
            /** Refused */
            refused: boolean | null;
            /** Created At */
            created_at: string;
            /** Citations */
            citations: components["schemas"]["CitationItem"][];
            /** Tool Executions */
            tool_executions: components["schemas"]["ToolExecutionItem"][];
        };
        /** MissingKnowledgeItem */
        MissingKnowledgeItem: {
            /** Id */
            id: number;
            /** Topic Key */
            topic_key: string;
            /** Sample Question */
            sample_question: string;
            /** Count */
            count: number;
            /** Missing Area */
            missing_area: string;
            status: components["schemas"]["MissingKnowledgeStatus"];
            /** Note */
            note: string | null;
            /** First Seen At */
            first_seen_at: string;
            /** Last Seen At */
            last_seen_at: string;
        };
        /**
         * MissingKnowledgeStatus
         * @enum {string}
         */
        MissingKnowledgeStatus: "PENDING" | "RESOLVED" | "IGNORED";
        /** MissingKnowledgeUpdate */
        MissingKnowledgeUpdate: {
            status: components["schemas"]["MissingKnowledgeStatus"];
            /** Note */
            note?: string | null;
        };
        /** PageResult[ChunkItem] */
        PageResult_ChunkItem_: {
            /** Items */
            items: components["schemas"]["ChunkItem"][];
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Total */
            total: number;
            /** Pages */
            pages: number;
        };
        /** PageResult[DocumentItem] */
        PageResult_DocumentItem_: {
            /** Items */
            items: components["schemas"]["DocumentItem"][];
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Total */
            total: number;
            /** Pages */
            pages: number;
        };
        /** PageResult[EvaluationCase] */
        PageResult_EvaluationCase_: {
            /** Items */
            items: components["schemas"]["EvaluationCase"][];
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Total */
            total: number;
            /** Pages */
            pages: number;
        };
        /** PageResult[EvaluationRunSummary] */
        PageResult_EvaluationRunSummary_: {
            /** Items */
            items: components["schemas"]["EvaluationRunSummary"][];
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Total */
            total: number;
            /** Pages */
            pages: number;
        };
        /** PageResult[ExperimentSummary] */
        PageResult_ExperimentSummary_: {
            /** Items */
            items: components["schemas"]["ExperimentSummary"][];
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Total */
            total: number;
            /** Pages */
            pages: number;
        };
        /** PageResult[MissingKnowledgeItem] */
        PageResult_MissingKnowledgeItem_: {
            /** Items */
            items: components["schemas"]["MissingKnowledgeItem"][];
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Total */
            total: number;
            /** Pages */
            pages: number;
        };
        /** SessionItem */
        SessionItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** ToolExecutionItem */
        ToolExecutionItem: {
            /**
             * Tool Name
             * @constant
             */
            tool_name: "generate_rights_material_checklist";
            input: components["schemas"]["MaterialChecklistInput"];
            output: components["schemas"]["MaterialChecklistOutput"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_HealthData_"];
                };
            };
        };
    };
    upload_document_api_documents_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_documents_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_DocumentUploadAccepted_"];
                };
            };
            /** @description Invalid business request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Resource state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Uploaded file is too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Business implementation is scheduled for a later phase */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description A required service is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
        };
    };
    list_documents_api_documents_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                status?: components["schemas"]["DocumentStatus"] | null;
                keyword?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_PageResult_DocumentItem__"];
                };
            };
            /** @description Invalid business request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Resource state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Uploaded file is too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Business implementation is scheduled for a later phase */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description A required service is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
        };
    };
    get_document_api_documents__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_DocumentItem_"];
                };
            };
            /** @description Invalid business request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Resource state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Uploaded file is too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Business implementation is scheduled for a later phase */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description A required service is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
        };
    };
    reimport_document_api_documents__id__reimport_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_DocumentReimportAccepted_"];
                };
            };
            /** @description Invalid business request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Resource state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Uploaded file is too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Business implementation is scheduled for a later phase */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description A required service is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
        };
    };
    list_document_chunks_api_documents__id__chunks_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_PageResult_ChunkItem__"];
                };
            };
            /** @description Invalid business request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Resource state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Uploaded file is too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Business implementation is scheduled for a later phase */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description A required service is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
        };
    };
    create_session_api_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_SessionItem_"];
                };
            };
            /** @description Invalid business request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Resource state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Uploaded file is too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description A required service is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
        };
    };
    list_session_messages_api_sessions__id__messages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_MessageItem__"];
                };
            };
            /** @description Invalid business request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Resource state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Uploaded file is too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description A required service is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
        };
    };
    stream_chat_api_chat_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description SSE events: optional tool, one or more token events, sources, then done; errors use a terminal error event. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Invalid business request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Resource state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Uploaded file is too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description A required service is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
        };
    };
    material_checklist_api_tools_material_checklist_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaterialChecklistInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ToolExecutionItem_"];
                };
            };
            /** @description Invalid business request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Resource state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Uploaded file is too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description A required service is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
        };
    };
    list_evaluation_cases_api_evaluations_cases_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                topic?: string | null;
                expected_type?: components["schemas"]["EvaluationExpectedType"] | null;
                is_multi_turn?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_PageResult_EvaluationCase__"];
                };
            };
            /** @description Invalid business request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Resource state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Uploaded file is too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description A required service is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
        };
    };
    list_evaluation_runs_api_evaluations_runs_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                status?: components["schemas"]["JobStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_PageResult_EvaluationRunSummary__"];
                };
            };
            /** @description Invalid business request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Resource state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Uploaded file is too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description A required service is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
        };
    };
    create_evaluation_run_api_evaluations_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluationRunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_EvaluationRunJob_"];
                };
            };
            /** @description Invalid business request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Resource state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Uploaded file is too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description A required service is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
        };
    };
    get_evaluation_run_api_evaluations_runs__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_EvaluationRunDetail_"];
                };
            };
            /** @description Invalid business request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Resource state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Uploaded file is too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description A required service is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
        };
    };
    list_missing_knowledge_api_missing_knowledge_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                status?: components["schemas"]["MissingKnowledgeStatus"] | null;
                keyword?: string | null;
                sort?: "count_desc" | "last_seen_desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_PageResult_MissingKnowledgeItem__"];
                };
            };
            /** @description Invalid business request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Resource state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Uploaded file is too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description A required service is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
        };
    };
    update_missing_knowledge_api_missing_knowledge__id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MissingKnowledgeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_MissingKnowledgeItem_"];
                };
            };
            /** @description Invalid business request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Resource state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Uploaded file is too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description A required service is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
        };
    };
    list_experiments_api_retrieval_experiments_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                status?: components["schemas"]["JobStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_PageResult_ExperimentSummary__"];
                };
            };
            /** @description Invalid business request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Resource state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Uploaded file is too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description A required service is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
        };
    };
    create_experiment_api_retrieval_experiments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ExperimentJob_"];
                };
            };
            /** @description Invalid business request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Resource state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Uploaded file is too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description A required service is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
        };
    };
    get_experiment_api_retrieval_experiments__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ExperimentDetail_"];
                };
            };
            /** @description Invalid business request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Resource state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Uploaded file is too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
            /** @description A required service is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_NoneType_"];
                };
            };
        };
    };
}
